name: Performance Evaluation Recurring Task

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,14 * *"
    
jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      # Check out is necessary to use issue template
      - uses: actions/checkout@v2
        
      - name: issue-bot
        uses: imjohnbo/issue-bot@v2
        with:
          assignees: ${{ github.actor }}
          labels: "Performance Evaluation"
          pinned: false
          close-previous: false
          title: "Performance Evaluation" 
          template: ".github/perfeval_issue_template.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
